services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Kitzberger\CliToolbox\Command\TreeCommand:
    tags:
      - name: 'console.command'
        command: 'toolbox:tree'
        schedulable: true
